/*
	Copyright (c) Microsoft Corporation.  All rights reserved.
*/


#define DispatchRoutine_SDV_RESULT
#define StartIoRoutine_SDV_RESULT
#define CancelRoutine_SDV_RESULT
#define IsrRoutine_SDV_RESULT
#define KeDpcRoutine_SDV_RESULT
#define IoDpcRoutine_SDV_RESULT
#define IoCompletion_SDV_RESULT
#define WorkerThread_SDV_RESULT
#define CheckAddDevice_SDV_RESULT
#define CheckIrpMjPnp_SDV_RESULT
#define CheckDriverUnload_SDV_RESULT
#define AddDeviceIoAttribCheck_SDV_RESULT
#define DoPowerPagable_SDV_RESULT
#define DoPowerInrush_SDV_RESULT
#define RemoveCheck_SDV_RESULT
#define RemoveCheck2_SDV_RESULT
#define IoAllocate_SDV_RESULT
#define IoBuildFsd_SDV_RESULT
#define IoBuildDeviceControl_SDV_RESULT
#define IoBuildSynchronousFsdRequest_SDV_RESULT
#define DanglingDeviceObjectCheck_SDV_RESULT
#define DriverEntryIoAttribCheck_SDV_RESULT
#define CheckBusDriver_SDV_RESULT
#define CheckIrpMjPower_SDV_RESULT
#define IsNonPnpDriver_SDV_RESULT
#define PowerPolicyOwner_SDV_RESULT
#define InitializeDpcRequest_SDV_RESULT
