/*
	Copyright (c) Microsoft Corporation.  All rights reserved.
*/

/*
    This file declares the driver entry points.
*/
#include <ndis.h>
#include <netioapi.h>

extern DRIVER_INITIALIZE fun_DriverEntry;


/*
In future we should just call slamscan mult. times with -update for each sub model that make up the list of overall models t
*/


#ifdef fun_MINIPORT_RESET
extern MINIPORT_RESET fun_MINIPORT_RESET;
#endif

#ifdef fun_MINIPORT_PAUSE
extern MINIPORT_PAUSE fun_MINIPORT_PAUSE;
#endif

#ifdef fun_MINIPORT_RESTART
extern MINIPORT_RESTART fun_MINIPORT_RESTART;
#endif

#ifdef fun_MINIPORT_INITIALIZE
extern MINIPORT_INITIALIZE fun_MINIPORT_INITIALIZE;
#endif

#ifdef fun_MINIPORT_HALT
extern MINIPORT_HALT fun_MINIPORT_HALT;
#endif

#ifdef fun_MINIPORT_OID_REQUEST
extern MINIPORT_OID_REQUEST fun_MINIPORT_OID_REQUEST;
#endif

#ifdef fun_MINIPORT_SHUTDOWN
extern MINIPORT_SHUTDOWN fun_MINIPORT_SHUTDOWN;
#endif

#ifdef fun_MINIPORT_DEVICE_PNP_EVENT_NOTIFY
extern MINIPORT_DEVICE_PNP_EVENT_NOTIFY fun_MINIPORT_DEVICE_PNP_EVENT_NOTIFY;
#endif

#ifdef fun_MINIPORT_CANCEL_SEND
extern MINIPORT_CANCEL_SEND fun_MINIPORT_CANCEL_SEND;
#endif

#ifdef fun_MINIPORT_CHECK_FOR_HANG
extern MINIPORT_CHECK_FOR_HANG fun_MINIPORT_CHECK_FOR_HANG;
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_1
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_1; /*multiple*/
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_2
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_2; /*multiple*/
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_3
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_3; /*multiple*/
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_4
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_4; /*multiple*/
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_5
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_5; /*multiple*/
#endif

#ifdef fun_MINIPORT_CANCEL_OID_REQUEST_6
extern MINIPORT_CANCEL_OID_REQUEST fun_MINIPORT_CANCEL_OID_REQUEST_6; /*multiple*/
#endif

#ifdef fun_MINIPORT_SEND_NET_BUFFER_LISTS
extern MINIPORT_SEND_NET_BUFFER_LISTS fun_MINIPORT_SEND_NET_BUFFER_LISTS;
#endif

#ifdef fun_MINIPORT_RETURN_NET_BUFFER_LISTS
extern MINIPORT_RETURN_NET_BUFFER_LISTS fun_MINIPORT_RETURN_NET_BUFFER_LISTS;
#endif

#ifdef fun_MINIPORT_UNLOAD
extern MINIPORT_UNLOAD fun_MINIPORT_UNLOAD;
#endif

#ifdef fun_MINIPORT_SET_OPTIONS
extern MINIPORT_SET_OPTIONS fun_MINIPORT_SET_OPTIONS;
#endif

#ifdef fun_MINIPORT_PROCESS_SG_LIST
extern MINIPORT_PROCESS_SG_LIST fun_MINIPORT_PROCESS_SG_LIST;
#endif

#ifdef fun_MINIPORT_ALLOCATE_SHARED_MEM_COMPLETE
extern MINIPORT_ALLOCATE_SHARED_MEM_COMPLETE fun_MINIPORT_ALLOCATE_SHARED_MEM_COMPLETE;
#endif



#ifdef fun_MINIPORT_ADD_DEVICE
extern MINIPORT_ADD_DEVICE fun_MINIPORT_ADD_DEVICE;
#endif

#ifdef fun_MINIPORT_START_DEVICE
extern MINIPORT_START_DEVICE fun_MINIPORT_START_DEVICE;
#endif

#ifdef fun_MINIPORT_REMOVE_DEVICE
extern MINIPORT_REMOVE_DEVICE fun_MINIPORT_REMOVE_DEVICE;
#endif

#ifdef fun_MINIPORT_FILTER_RESOURCE_REQUIREMENTS
extern MINIPORT_FILTER_RESOURCE_REQUIREMENTS fun_MINIPORT_FILTER_RESOURCE_REQUIREMENTS;
#endif




#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_1
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_1; /*multiple*/
#endif

#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_2
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_2; /*multiple*/
#endif

#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_3
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_3; /*multiple*/
#endif

#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_4
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_4; /*multiple*/
#endif

#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_5
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_5; /*multiple*/
#endif

#ifdef fun_NDIS_IO_WORKITEM_FUNCTION_6
extern NDIS_IO_WORKITEM_FUNCTION fun_NDIS_IO_WORKITEM_FUNCTION_6; /*multiple*/
#endif


#ifdef fun_MINIPORT_ISR_1
extern MINIPORT_ISR fun_MINIPORT_ISR_1; /*multiple*/
#endif

#ifdef fun_MINIPORT_ISR_2
extern MINIPORT_ISR fun_MINIPORT_ISR_2; /*multiple*/
#endif

#ifdef fun_MINIPORT_ISR_3
extern MINIPORT_ISR fun_MINIPORT_ISR_3; /*multiple*/
#endif

#ifdef fun_MINIPORT_ISR_4
extern MINIPORT_ISR fun_MINIPORT_ISR_4; /*multiple*/
#endif

#ifdef fun_MINIPORT_ISR_5
extern MINIPORT_ISR fun_MINIPORT_ISR_5; /*multiple*/
#endif

#ifdef fun_MINIPORT_ISR_6
extern MINIPORT_ISR fun_MINIPORT_ISR_6; /*multiple*/
#endif


#ifdef fun_MINIPORT_INTERRUPT_DPC_1
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_INTERRUPT_DPC_2
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_INTERRUPT_DPC_3
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_INTERRUPT_DPC_4
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_INTERRUPT_DPC_5
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_INTERRUPT_DPC_6
extern MINIPORT_INTERRUPT_DPC fun_MINIPORT_INTERRUPT_DPC_6;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_1
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_2
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_3
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_4
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_5
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_INTERRUPT_6
extern MINIPORT_ENABLE_INTERRUPT fun_MINIPORT_ENABLE_INTERRUPT_6;  /*multiple*/
#endif


#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_1
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_2
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_3
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_4
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_5
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_INTERRUPT_6
extern MINIPORT_SYNCHRONIZE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_INTERRUPT_6;  /*multiple*/
#endif



#ifdef fun_MINIPORT_DISABLE_INTERRUPT_1
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_INTERRUPT_2
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_INTERRUPT_3
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_INTERRUPT_4
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_INTERRUPT_5
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_INTERRUPT_6
extern MINIPORT_DISABLE_INTERRUPT fun_MINIPORT_DISABLE_INTERRUPT_6;  /*multiple*/
#endif


#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_1
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_1; /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_2
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_2; /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_3
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_3; /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_4
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_4; /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_5
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_5; /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_6
extern MINIPORT_MESSAGE_INTERRUPT fun_MINIPORT_MESSAGE_INTERRUPT_6; /*multiple*/
#endif


#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_1
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_2
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_3
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_4
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_5
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_MESSAGE_INTERRUPT_DPC_6
extern MINIPORT_MESSAGE_INTERRUPT_DPC fun_MINIPORT_MESSAGE_INTERRUPT_DPC_6;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_1
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_2
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_3
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_4
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_5
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_6
extern MINIPORT_ENABLE_MESSAGE_INTERRUPT fun_MINIPORT_ENABLE_MESSAGE_INTERRUPT_6;  /*multiple*/
#endif


#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_1
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_2
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_3
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_4
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_5
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_6
extern MINIPORT_DISABLE_MESSAGE_INTERRUPT fun_MINIPORT_DISABLE_MESSAGE_INTERRUPT_6;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_1
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_1;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_2
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_2;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_3
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_3;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_4
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_4;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_5
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_5;  /*multiple*/
#endif

#ifdef fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_6
extern MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT fun_MINIPORT_SYNCHRONIZE_MESSAGE_INTERRUPT_6;  /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_1
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_1;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_2
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_2;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_3
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_3;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_4
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_4;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_5
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_5;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_6
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_6;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_7
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_7;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_8
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_8;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_9
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_9;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_10
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_10;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_11
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_11;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_12
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_12;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_13
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_13;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_14
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_14;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_15
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_15;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_16
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_16;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_17
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_17;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_18
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_18;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_19
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_19;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_20
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_20;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_21
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_21;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_22
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_22;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_23
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_23;   /*multiple*/
#endif

#ifdef fun_NDIS_TIMER_FUNCTION_24
extern NDIS_TIMER_FUNCTION fun_NDIS_TIMER_FUNCTION_24;   /*multiple*/
#endif


#ifdef fun_MINIPORT_DIRECT_OID_REQUEST
extern MINIPORT_DIRECT_OID_REQUEST fun_MINIPORT_DIRECT_OID_REQUEST;
#endif

#ifdef fun_MINIPORT_CANCEL_DIRECT_OID_REQUEST
extern MINIPORT_CANCEL_DIRECT_OID_REQUEST fun_MINIPORT_CANCEL_DIRECT_OID_REQUEST;
#endif


#ifdef fun_MINIPORT_CO_ACTIVATE_VC
extern MINIPORT_CO_ACTIVATE_VC fun_MINIPORT_CO_ACTIVATE_VC;
#endif 

#ifdef fun_MINIPORT_CO_CREATE_VC
extern MINIPORT_CO_CREATE_VC fun_MINIPORT_CO_CREATE_VC;
#endif 

#ifdef fun_MINIPORT_CO_DEACTIVATE_VC
extern MINIPORT_CO_DEACTIVATE_VC fun_MINIPORT_CO_DEACTIVATE_VC;
#endif 

#ifdef fun_MINIPORT_CO_DELETE_VC
extern MINIPORT_CO_DELETE_VC fun_MINIPORT_CO_DELETE_VC;
#endif 

#ifdef fun_MINIPORT_CO_OID_REQUEST
extern MINIPORT_CO_OID_REQUEST fun_MINIPORT_CO_OID_REQUEST;
#endif 

#ifdef fun_MINIPORT_CO_SEND_NET_BUFFER_LISTS
extern MINIPORT_CO_SEND_NET_BUFFER_LISTS fun_MINIPORT_CO_SEND_NET_BUFFER_LISTS;
#endif 


#ifdef fun_FILTER_ATTACH
extern FILTER_ATTACH fun_FILTER_ATTACH;
#endif

#ifdef fun_FILTER_CANCEL_DIRECT_OID_REQUEST
extern FILTER_CANCEL_DIRECT_OID_REQUEST fun_FILTER_CANCEL_DIRECT_OID_REQUEST;
#endif

#ifdef fun_FILTER_CANCEL_OID_REQUEST
extern FILTER_CANCEL_OID_REQUEST fun_FILTER_CANCEL_OID_REQUEST;
#endif

#ifdef fun_FILTER_CANCEL_SEND_NET_BUFFER_LISTS
extern FILTER_CANCEL_SEND_NET_BUFFER_LISTS fun_FILTER_CANCEL_SEND_NET_BUFFER_LISTS;
#endif

#ifdef fun_FILTER_DETACH
extern FILTER_DETACH fun_FILTER_DETACH;
#endif

#ifdef fun_FILTER_DEVICE_PNP_EVENT_NOTIFY
extern FILTER_DEVICE_PNP_EVENT_NOTIFY fun_FILTER_DEVICE_PNP_EVENT_NOTIFY;
#endif

#ifdef fun_FILTER_DIRECT_OID_REQUEST
extern FILTER_DIRECT_OID_REQUEST fun_FILTER_DIRECT_OID_REQUEST;
#endif

#ifdef fun_FILTER_DIRECT_OID_REQUEST_COMPLETE
extern FILTER_DIRECT_OID_REQUEST_COMPLETE fun_FILTER_DIRECT_OID_REQUEST_COMPLETE;
#endif

#ifdef fun_FILTER_DRIVER_UNLOAD
extern DRIVER_UNLOAD fun_FILTER_DRIVER_UNLOAD;
#endif

#ifdef fun_FILTER_NET_PNP_EVENT
extern FILTER_NET_PNP_EVENT fun_FILTER_NET_PNP_EVENT;
#endif

#ifdef fun_FILTER_OID_REQUEST
extern FILTER_OID_REQUEST fun_FILTER_OID_REQUEST;
#endif

#ifdef fun_FILTER_OID_REQUEST_COMPLETE
extern FILTER_OID_REQUEST_COMPLETE fun_FILTER_OID_REQUEST_COMPLETE;
#endif

#ifdef fun_FILTER_PAUSE
extern FILTER_PAUSE fun_FILTER_PAUSE;
#endif

#ifdef fun_FILTER_RECEIVE_NET_BUFFER_LISTS
extern FILTER_RECEIVE_NET_BUFFER_LISTS fun_FILTER_RECEIVE_NET_BUFFER_LISTS;
#endif

#ifdef fun_FILTER_RESTART
extern FILTER_RESTART fun_FILTER_RESTART;
#endif

#ifdef fun_FILTER_RETURN_NET_BUFFER_LISTS
extern FILTER_RETURN_NET_BUFFER_LISTS fun_FILTER_RETURN_NET_BUFFER_LISTS;
#endif
   
#ifdef fun_FILTER_SEND_NET_BUFFER_LISTS
extern FILTER_SEND_NET_BUFFER_LISTS fun_FILTER_SEND_NET_BUFFER_LISTS;
#endif

#ifdef fun_FILTER_SEND_NET_BUFFER_LISTS_COMPLETE
extern FILTER_SEND_NET_BUFFER_LISTS_COMPLETE fun_FILTER_SEND_NET_BUFFER_LISTS_COMPLETE;
#endif

#ifdef fun_FILTER_SET_MODULE_OPTIONS
extern FILTER_SET_MODULE_OPTIONS fun_FILTER_SET_MODULE_OPTIONS;
#endif

#ifdef fun_FILTER_SET_OPTIONS
extern FILTER_SET_OPTIONS fun_FILTER_SET_OPTIONS;
#endif

#ifdef fun_FILTER_STATUS
extern FILTER_STATUS fun_FILTER_STATUS;
#endif


#ifdef fun_PROTOCOL_BIND_ADAPTER_EX
extern PROTOCOL_BIND_ADAPTER_EX fun_PROTOCOL_BIND_ADAPTER_EX;
#endif

#ifdef fun_PROTOCOL_CLOSE_ADAPTER_COMPLETE_EX
extern PROTOCOL_CLOSE_ADAPTER_COMPLETE_EX fun_PROTOCOL_CLOSE_ADAPTER_COMPLETE_EX;
#endif

#ifdef fun_PROTOCOL_DIRECT_OID_REQUEST_COMPLETE
extern PROTOCOL_DIRECT_OID_REQUEST_COMPLETE fun_PROTOCOL_DIRECT_OID_REQUEST_COMPLETE;
#endif

#ifdef fun_PROTOCOL_NET_PNP_EVENT
extern PROTOCOL_NET_PNP_EVENT fun_PROTOCOL_NET_PNP_EVENT;
#endif

#ifdef fun_PROTOCOL_OID_REQUEST_COMPLETE
extern PROTOCOL_OID_REQUEST_COMPLETE fun_PROTOCOL_OID_REQUEST_COMPLETE;
#endif

#ifdef fun_PROTOCOL_OPEN_ADAPTER_COMPLETE_EX
extern PROTOCOL_OPEN_ADAPTER_COMPLETE_EX fun_PROTOCOL_OPEN_ADAPTER_COMPLETE_EX;
#endif

#ifdef fun_PROTOCOL_RECEIVE_NET_BUFFER_LISTS
extern PROTOCOL_RECEIVE_NET_BUFFER_LISTS fun_PROTOCOL_RECEIVE_NET_BUFFER_LISTS;
#endif

#ifdef fun_PROTOCOL_SEND_NET_BUFFER_LISTS_COMPLETE
extern PROTOCOL_SEND_NET_BUFFER_LISTS_COMPLETE fun_PROTOCOL_SEND_NET_BUFFER_LISTS_COMPLETE;
#endif

#ifdef fun_PROTOCOL_SET_OPTIONS
extern PROTOCOL_SET_OPTIONS fun_PROTOCOL_SET_OPTIONS;
#endif

#ifdef fun_PROTOCOL_STATUS_EX
extern PROTOCOL_STATUS_EX fun_PROTOCOL_STATUS_EX;
#endif

#ifdef fun_PROTOCOL_UNBIND_ADAPTER_EX
extern PROTOCOL_UNBIND_ADAPTER_EX fun_PROTOCOL_UNBIND_ADAPTER_EX;
#endif

#ifdef fun_PROTOCOL_UNINSTALL
extern PROTOCOL_UNINSTALL fun_PROTOCOL_UNINSTALL;
#endif

#ifdef fun_PROTOCOL_UNLOAD
extern PROTOCOL_UNLOAD fun_PROTOCOL_UNLOAD;
#endif  


#ifdef fun_PROTOCOL_CL_ADD_PARTY_COMPLETE
extern PROTOCOL_CL_ADD_PARTY_COMPLETE fun_PROTOCOL_CL_ADD_PARTY_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_CALL_CONNECTED
extern PROTOCOL_CL_CALL_CONNECTED fun_PROTOCOL_CL_CALL_CONNECTED;
#endif 

#ifdef fun_PROTOCOL_CL_CLOSE_AF_COMPLETE
extern PROTOCOL_CL_CLOSE_AF_COMPLETE fun_PROTOCOL_CL_CLOSE_AF_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_CLOSE_CALL_COMPLETE
extern PROTOCOL_CL_CLOSE_CALL_COMPLETE fun_PROTOCOL_CL_CLOSE_CALL_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_DEREGISTER_SAP_COMPLETE
extern PROTOCOL_CL_DEREGISTER_SAP_COMPLETE fun_PROTOCOL_CL_DEREGISTER_SAP_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_DROP_PARTY_COMPLETE
extern PROTOCOL_CL_DROP_PARTY_COMPLETE fun_PROTOCOL_CL_DROP_PARTY_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_INCOMING_CALL
extern PROTOCOL_CL_INCOMING_CALL fun_PROTOCOL_CL_INCOMING_CALL;
#endif 

#ifdef fun_PROTOCOL_CL_INCOMING_CALL_QOS_CHANGE
extern PROTOCOL_CL_INCOMING_CALL_QOS_CHANGE fun_PROTOCOL_CL_INCOMING_CALL_QOS_CHANGE;
#endif 

#ifdef fun_PROTOCOL_CL_INCOMING_CLOSE_CALL
extern PROTOCOL_CL_INCOMING_CLOSE_CALL fun_PROTOCOL_CL_INCOMING_CLOSE_CALL;
#endif 

#ifdef fun_PROTOCOL_CL_INCOMING_DROP_PARTY
extern PROTOCOL_CL_INCOMING_DROP_PARTY fun_PROTOCOL_CL_INCOMING_DROP_PARTY;
#endif 

#ifdef fun_PROTOCOL_CL_MAKE_CALL_COMPLETE
extern PROTOCOL_CL_MAKE_CALL_COMPLETE fun_PROTOCOL_CL_MAKE_CALL_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_MODIFY_CALL_QOS_COMPLETE
extern PROTOCOL_CL_MODIFY_CALL_QOS_COMPLETE fun_PROTOCOL_CL_MODIFY_CALL_QOS_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_NOTIFY_CLOSE_AF
extern PROTOCOL_CL_NOTIFY_CLOSE_AF fun_PROTOCOL_CL_NOTIFY_CLOSE_AF;
#endif 

#ifdef fun_PROTOCOL_CL_OPEN_AF_COMPLETE
extern PROTOCOL_CL_OPEN_AF_COMPLETE fun_PROTOCOL_CL_OPEN_AF_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CL_OPEN_AF_COMPLETE_EX
extern PROTOCOL_CL_OPEN_AF_COMPLETE_EX fun_PROTOCOL_CL_OPEN_AF_COMPLETE_EX;
#endif 

#ifdef fun_PROTOCOL_CL_REGISTER_SAP_COMPLETE
extern PROTOCOL_CL_REGISTER_SAP_COMPLETE fun_PROTOCOL_CL_REGISTER_SAP_COMPLETE;
#endif 


#ifdef fun_PROTOCOL_CM_ACTIVATE_VC_COMPLETE
extern PROTOCOL_CM_ACTIVATE_VC_COMPLETE fun_PROTOCOL_CM_ACTIVATE_VC_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CM_ADD_PARTY
extern PROTOCOL_CM_ADD_PARTY fun_PROTOCOL_CM_ADD_PARTY;
#endif 

#ifdef fun_PROTOCOL_CM_CLOSE_AF
extern PROTOCOL_CM_CLOSE_AF fun_PROTOCOL_CM_CLOSE_AF;
#endif 

#ifdef fun_PROTOCOL_CM_CLOSE_CALL
extern PROTOCOL_CM_CLOSE_CALL fun_PROTOCOL_CM_CLOSE_CALL;
#endif 

#ifdef fun_PROTOCOL_CM_DEACTIVATE_VC_COMPLETE
extern PROTOCOL_CM_DEACTIVATE_VC_COMPLETE fun_PROTOCOL_CM_DEACTIVATE_VC_COMPLETE;
#endif 

#ifdef fun_PROTOCOL_CM_DEREGISTER_SAP
extern PROTOCOL_CM_DEREGISTER_SAP fun_PROTOCOL_CM_DEREGISTER_SAP;
#endif 

#ifdef fun_PROTOCOL_CM_DROP_PARTY
extern PROTOCOL_CM_DROP_PARTY fun_PROTOCOL_CM_DROP_PARTY;
#endif 
 
#ifdef fun_PROTOCOL_CM_INCOMING_CALL_COMPLETE
extern PROTOCOL_CM_INCOMING_CALL_COMPLETE fun_PROTOCOL_CM_INCOMING_CALL_COMPLETE;
#endif 
 
#ifdef fun_PROTOCOL_CM_MAKE_CALL
extern PROTOCOL_CM_MAKE_CALL fun_PROTOCOL_CM_MAKE_CALL;
#endif 
  
#ifdef fun_PROTOCOL_CM_MODIFY_QOS_CALL
extern PROTOCOL_CM_MODIFY_QOS_CALL fun_PROTOCOL_CM_MODIFY_QOS_CALL;
#endif 
  
#ifdef fun_PROTOCOL_CM_NOTIFY_CLOSE_AF_COMPLETE
extern PROTOCOL_CM_NOTIFY_CLOSE_AF_COMPLETE fun_PROTOCOL_CM_NOTIFY_CLOSE_AF_COMPLETE;
#endif 
 
#ifdef fun_PROTOCOL_CM_OPEN_AF
extern PROTOCOL_CM_OPEN_AF fun_PROTOCOL_CM_OPEN_AF;
#endif 
 
#ifdef fun_PROTOCOL_CM_REG_SAP
extern PROTOCOL_CM_REG_SAP fun_PROTOCOL_CM_REG_SAP;
#endif 
 

#ifdef fun_PROTOCOL_CO_AF_REGISTER_NOTIFY
extern PROTOCOL_CO_AF_REGISTER_NOTIFY fun_PROTOCOL_CO_AF_REGISTER_NOTIFY;
#endif 
 
#ifdef fun_PROTOCOL_CO_CREATE_VC
extern PROTOCOL_CO_CREATE_VC fun_PROTOCOL_CO_CREATE_VC;
#endif 
 
#ifdef fun_PROTOCOL_CO_DELETE_VC
extern PROTOCOL_CO_DELETE_VC fun_PROTOCOL_CO_DELETE_VC;
#endif 

#ifdef fun_PROTOCOL_CO_OID_REQUEST
extern PROTOCOL_CO_OID_REQUEST fun_PROTOCOL_CO_OID_REQUEST;
#endif 
 
#ifdef fun_PROTOCOL_CO_OID_REQUEST_COMPLETE
extern PROTOCOL_CO_OID_REQUEST_COMPLETE fun_PROTOCOL_CO_OID_REQUEST_COMPLETE;
#endif 
 
#ifdef fun_PROTOCOL_CO_RECEIVE_NET_BUFFER_LISTS
extern PROTOCOL_CO_RECEIVE_NET_BUFFER_LISTS fun_PROTOCOL_CO_RECEIVE_NET_BUFFER_LISTS;
#endif 
#ifdef fun_PROTOCOL_CO_SEND_NET_BUFFER_LISTS_COMPLETE
extern PROTOCOL_CO_SEND_NET_BUFFER_LISTS_COMPLETE fun_PROTOCOL_CO_SEND_NET_BUFFER_LISTS_COMPLETE;
#endif 
 
#ifdef fun_PROTOCOL_CO_STATUS_EX
extern PROTOCOL_CO_STATUS_EX fun_PROTOCOL_CO_STATUS_EX;
#endif 


#ifdef fun_IF_QUERY_OBJECT_1
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_1;  /*multiple*/
#endif

#ifdef fun_IF_QUERY_OBJECT_2
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_2;  /*multiple*/
#endif

#ifdef fun_IF_QUERY_OBJECT_3
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_3;  /*multiple*/
#endif

#ifdef fun_IF_QUERY_OBJECT_4
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_4;  /*multiple*/
#endif

#ifdef fun_IF_QUERY_OBJECT_5
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_5;  /*multiple*/
#endif

#ifdef fun_IF_QUERY_OBJECT_6
extern IF_QUERY_OBJECT fun_IF_QUERY_OBJECT_6;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_1
extern IF_SET_OBJECT fun_IF_SET_OBJECT_1;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_2
extern IF_SET_OBJECT fun_IF_SET_OBJECT_2;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_3
extern IF_SET_OBJECT fun_IF_SET_OBJECT_3;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_4
extern IF_SET_OBJECT fun_IF_SET_OBJECT_4;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_5
extern IF_SET_OBJECT fun_IF_SET_OBJECT_5;  /*multiple*/
#endif

#ifdef fun_IF_SET_OBJECT_6
extern IF_SET_OBJECT fun_IF_SET_OBJECT_6;  /*multiple*/
#endif


#if defined(fun_WDF_USB_READERS_FAILED_1) || \
	defined(fun_WDF_USB_READERS_FAILED_2) || \
	defined(fun_WDF_USB_READERS_FAILED_3) ||\
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_1) || \
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_2) || \
	defined(fun_WDF_USB_READER_COMPLETION_ROUTINE_3) 
  #define SDV_USB_SUPPORT 1
#endif

#if defined(SDV_USB_SUPPORT)
    #include "usbdi.h"
    #include "usbdlib.h"
#endif
#pragma warning(disable:4200)
#include <wdf.h>
#pragma warning(default:4200)
#if defined(SDV_USB_SUPPORT)
    #include <wdfusb.h>
#endif

#ifdef fun_WDF_DEVICE_ARM_WAKE_FROM_S0
extern EVT_WDF_DEVICE_ARM_WAKE_FROM_S0 fun_WDF_DEVICE_ARM_WAKE_FROM_S0; 
#endif
#ifdef fun_WDF_DEVICE_ARM_WAKE_FROM_SX
extern EVT_WDF_DEVICE_ARM_WAKE_FROM_SX fun_WDF_DEVICE_ARM_WAKE_FROM_SX; 
#endif
#ifdef fun_WDF_DEVICE_ARM_WAKE_FROM_SX_WITH_REASON
extern EVT_WDF_DEVICE_ARM_WAKE_FROM_SX_WITH_REASON fun_WDF_DEVICE_ARM_WAKE_FROM_SX_WITH_REASON; 
#endif
#ifdef fun_WDF_DEVICE_D0_ENTRY
extern EVT_WDF_DEVICE_D0_ENTRY fun_WDF_DEVICE_D0_ENTRY; 
#endif
#ifdef fun_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED
extern EVT_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED fun_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED; 
#endif
#ifdef fun_WDF_DEVICE_D0_EXIT
extern EVT_WDF_DEVICE_D0_EXIT fun_WDF_DEVICE_D0_EXIT; 
#endif
#ifdef fun_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED
extern EVT_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED fun_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED; 
#endif
#ifdef fun_WDF_DEVICE_DISARM_WAKE_FROM_S0
extern EVT_WDF_DEVICE_DISARM_WAKE_FROM_S0 fun_WDF_DEVICE_DISARM_WAKE_FROM_S0; 
#endif
#ifdef fun_WDF_DEVICE_DISARM_WAKE_FROM_SX
extern EVT_WDF_DEVICE_DISARM_WAKE_FROM_SX fun_WDF_DEVICE_DISARM_WAKE_FROM_SX; 
#endif
#ifdef fun_WDF_DEVICE_FILE_CREATE
extern EVT_WDF_DEVICE_FILE_CREATE fun_WDF_DEVICE_FILE_CREATE; 
#endif
#ifdef fun_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION
extern EVT_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION fun_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_PREPARE_HARDWARE
extern EVT_WDF_DEVICE_PREPARE_HARDWARE fun_WDF_DEVICE_PREPARE_HARDWARE; 
#endif
#ifdef fun_WDF_DEVICE_QUERY_STOP
extern EVT_WDF_DEVICE_QUERY_STOP fun_WDF_DEVICE_QUERY_STOP; 
#endif
#ifdef fun_WDF_DEVICE_QUERY_REMOVE
extern EVT_WDF_DEVICE_QUERY_REMOVE fun_WDF_DEVICE_QUERY_REMOVE; 
#endif
#ifdef fun_WDF_DEVICE_RELATIONS_QUERY
extern EVT_WDF_DEVICE_RELATIONS_QUERY fun_WDF_DEVICE_RELATIONS_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_RELEASE_HARDWARE
extern EVT_WDF_DEVICE_RELEASE_HARDWARE fun_WDF_DEVICE_RELEASE_HARDWARE; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP fun_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_FLUSH
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_FLUSH fun_WDF_DEVICE_SELF_MANAGED_IO_FLUSH; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_INIT
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_INIT fun_WDF_DEVICE_SELF_MANAGED_IO_INIT; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND fun_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND; 
#endif
#ifdef fun_WDF_DEVICE_SELF_MANAGED_IO_RESTART
extern EVT_WDF_DEVICE_SELF_MANAGED_IO_RESTART fun_WDF_DEVICE_SELF_MANAGED_IO_RESTART; 
#endif
#ifdef fun_WDF_DEVICE_SURPRISE_REMOVAL
extern EVT_WDF_DEVICE_SURPRISE_REMOVAL fun_WDF_DEVICE_SURPRISE_REMOVAL; 
#endif
#ifdef fun_WDF_DEVICE_USAGE_NOTIFICATION
extern EVT_WDF_DEVICE_USAGE_NOTIFICATION fun_WDF_DEVICE_USAGE_NOTIFICATION; 
#endif
#ifdef fun_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED
extern EVT_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED fun_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED; 
#endif
#ifdef fun_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED
extern EVT_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED fun_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED; 
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_1
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_1; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_1
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_1; /*multiple*/
#endif
#ifdef fun_WDF_IO_IN_CALLER_CONTEXT
extern EVT_WDF_IO_IN_CALLER_CONTEXT fun_WDF_IO_IN_CALLER_CONTEXT; 
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_2
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_2; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_3
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_3; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_4
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_4; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_5
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_5; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_PREPROCESS_6
extern EVT_WDFDEVICE_WDM_IRP_PREPROCESS fun_WDFDEVICE_WDM_IRP_PREPROCESS_6; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_2
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_2; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_3
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_3; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_4
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_4; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_5
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_5; /*multiple*/
#endif
#ifdef fun_WDFDEVICE_WDM_IRP_DISPATCH_6
extern EVT_WDFDEVICE_WDM_IRP_DISPATCH fun_WDFDEVICE_WDM_IRP_DISPATCH_6; /*multiple*/
#endif

#ifdef fun_WDF_DEVICE_SHUTDOWN_NOTIFICATION
extern EVT_WDF_DEVICE_SHUTDOWN_NOTIFICATION fun_WDF_DEVICE_SHUTDOWN_NOTIFICATION; 
#endif


#ifdef fun_WDF_DEVICE_CONTEXT_CLEANUP
extern EVT_WDF_DEVICE_CONTEXT_CLEANUP fun_WDF_DEVICE_CONTEXT_CLEANUP; 
#endif
#ifdef fun_WDF_DEVICE_CONTEXT_DESTROY
extern EVT_WDF_DEVICE_CONTEXT_DESTROY fun_WDF_DEVICE_CONTEXT_DESTROY; 
#endif
#ifdef fun_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK
extern EVT_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK fun_WDF_IO_QUEUE_CONTEXT_CLEANUP_CALLBACK; 
#endif
#ifdef fun_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK
extern EVT_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK fun_WDF_IO_QUEUE_CONTEXT_DESTROY_CALLBACK; 
#endif
#ifdef fun_WDF_FILE_CONTEXT_CLEANUP_CALLBACK
extern EVT_WDF_FILE_CONTEXT_CLEANUP_CALLBACK fun_WDF_FILE_CONTEXT_CLEANUP_CALLBACK; 
#endif
#ifdef fun_WDF_FILE_CONTEXT_DESTROY_CALLBACK
extern EVT_WDF_FILE_CONTEXT_DESTROY_CALLBACK fun_WDF_FILE_CONTEXT_DESTROY_CALLBACK; 
#endif


#ifdef fun_WDF_FILE_CLOSE
extern EVT_WDF_FILE_CLOSE fun_WDF_FILE_CLOSE; 
#endif
#ifdef fun_WDF_FILE_CLEANUP
extern EVT_WDF_FILE_CLEANUP fun_WDF_FILE_CLEANUP; 
#endif
#ifdef fun_WDF_DMA_ENABLER_FILL
extern EVT_WDF_DMA_ENABLER_FILL fun_WDF_DMA_ENABLER_FILL; 
#endif
#ifdef fun_WDF_DMA_ENABLER_FLUSH
extern EVT_WDF_DMA_ENABLER_FLUSH fun_WDF_DMA_ENABLER_FLUSH; 
#endif
#ifdef fun_WDF_DMA_ENABLER_ENABLE
extern EVT_WDF_DMA_ENABLER_ENABLE fun_WDF_DMA_ENABLER_ENABLE; 
#endif
#ifdef fun_WDF_DMA_ENABLER_DISABLE
extern EVT_WDF_DMA_ENABLER_DISABLE fun_WDF_DMA_ENABLER_DISABLE; 
#endif
#ifdef fun_WDF_DMA_ENABLER_SELFMANAGED_IO_START
extern EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_START fun_WDF_DMA_ENABLER_SELFMANAGED_IO_START; 
#endif
#ifdef fun_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP
extern EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP fun_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP; 
#endif
#ifdef fun_WDF_PROGRAM_DMA_1
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_1; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_2
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_2; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_3
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_3; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_4
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_4; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_5
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_5; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_6
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_6; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_7
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_7; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_8
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_8; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_9
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_9; /*multiple*/
#endif
#ifdef fun_WDF_PROGRAM_DMA_10
extern EVT_WDF_PROGRAM_DMA fun_WDF_PROGRAM_DMA_10; /*multiple*/
#endif
#ifdef fun_WDF_DPC_1
extern EVT_WDF_DPC fun_WDF_DPC_1; /*multiple*/
#endif
#ifdef fun_WDF_DPC_2
extern EVT_WDF_DPC fun_WDF_DPC_2; /*multiple*/
#endif
#ifdef fun_WDF_DPC_3
extern EVT_WDF_DPC fun_WDF_DPC_3; /*multiple*/
#endif
#ifdef fun_WDF_DPC_4
extern EVT_WDF_DPC fun_WDF_DPC_4; /*multiple*/
#endif
#ifdef fun_WDF_DPC_5
extern EVT_WDF_DPC fun_WDF_DPC_5; /*multiple*/
#endif
#ifdef fun_WDF_DPC_6
extern EVT_WDF_DPC fun_WDF_DPC_6; /*multiple*/
#endif
#ifdef fun_WDF_DPC_7
extern EVT_WDF_DPC fun_WDF_DPC_7; /*multiple*/
#endif
#ifdef fun_WDF_DRIVER_UNLOAD
extern EVT_WDF_DRIVER_UNLOAD fun_WDF_DRIVER_UNLOAD; 
#endif
#ifdef fun_WDF_INTERRUPT_ISR
extern EVT_WDF_INTERRUPT_ISR fun_WDF_INTERRUPT_ISR; 
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_1
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_1; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_2
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_2; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_3
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_3; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_4
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_4; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_5
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_5; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_6
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_6; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_7
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_7; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_8
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_8; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_9
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_9; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_10
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_10; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_SYNCHRONIZE_11
extern EVT_WDF_INTERRUPT_SYNCHRONIZE fun_WDF_INTERRUPT_SYNCHRONIZE_11; /*multiple*/
#endif
#ifdef fun_WDF_INTERRUPT_DPC
extern EVT_WDF_INTERRUPT_DPC fun_WDF_INTERRUPT_DPC; 
#endif
#ifdef fun_WDF_INTERRUPT_ENABLE
extern EVT_WDF_INTERRUPT_ENABLE fun_WDF_INTERRUPT_ENABLE; 
#endif
#ifdef fun_WDF_INTERRUPT_DISABLE
extern EVT_WDF_INTERRUPT_DISABLE fun_WDF_INTERRUPT_DISABLE; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_DEFAULT
extern EVT_WDF_IO_QUEUE_IO_DEFAULT fun_WDF_IO_QUEUE_IO_DEFAULT; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_STOP
extern EVT_WDF_IO_QUEUE_IO_STOP fun_WDF_IO_QUEUE_IO_STOP; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_RESUME
extern EVT_WDF_IO_QUEUE_IO_RESUME fun_WDF_IO_QUEUE_IO_RESUME; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_READ
extern EVT_WDF_IO_QUEUE_IO_READ fun_WDF_IO_QUEUE_IO_READ; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_WRITE
extern EVT_WDF_IO_QUEUE_IO_WRITE fun_WDF_IO_QUEUE_IO_WRITE; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL
extern EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL
extern EVT_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL fun_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL; 
#endif
#ifdef fun_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE
extern EVT_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE fun_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE; 
#endif
#ifdef fun_SDV_WDF_IO_QUEUE_STATE
extern EVT_WDF_IO_QUEUE_STATE fun_SDV_WDF_IO_QUEUE_STATE; 
#endif
#ifdef fun_WDF_IO_TARGET_QUERY_REMOVE
extern EVT_WDF_IO_TARGET_QUERY_REMOVE fun_WDF_IO_TARGET_QUERY_REMOVE; 
#endif
#ifdef fun_WDF_IO_TARGET_REMOVE_CANCELED
extern EVT_WDF_IO_TARGET_REMOVE_CANCELED fun_WDF_IO_TARGET_REMOVE_CANCELED; 
#endif
#ifdef fun_WDF_IO_TARGET_REMOVE_COMPLETE
extern EVT_WDF_IO_TARGET_REMOVE_COMPLETE fun_WDF_IO_TARGET_REMOVE_COMPLETE; 
#endif
#ifdef fun_WDF_OBJECT_CONTEXT_CLEANUP
extern EVT_WDF_OBJECT_CONTEXT_CLEANUP fun_WDF_OBJECT_CONTEXT_CLEANUP; 
#endif
#ifdef fun_WDF_OBJECT_CONTEXT_DESTROY
extern EVT_WDF_OBJECT_CONTEXT_DESTROY fun_WDF_OBJECT_CONTEXT_DESTROY; 
#endif
#ifdef fun_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST
extern EVT_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST fun_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST; 
#endif
#ifdef fun_WDF_REQUEST_CANCEL_1
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_1; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_2
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_2; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_3
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_3; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_4
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_4; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_5
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_5; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_CANCEL_6
extern EVT_WDF_REQUEST_CANCEL fun_WDF_REQUEST_CANCEL_6; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_1
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_1; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_2
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_2; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_3
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_3; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_4
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_4; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_5
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_5; /*multiple*/
#endif
#ifdef fun_WDF_REQUEST_COMPLETION_ROUTINE_6
extern EVT_WDF_REQUEST_COMPLETION_ROUTINE fun_WDF_REQUEST_COMPLETION_ROUTINE_6; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_1
extern EVT_WDF_TIMER fun_WDF_TIMER_1; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_2
extern EVT_WDF_TIMER fun_WDF_TIMER_2; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_3
extern EVT_WDF_TIMER fun_WDF_TIMER_3; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_4
extern EVT_WDF_TIMER fun_WDF_TIMER_4; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_5
extern EVT_WDF_TIMER fun_WDF_TIMER_5; /*multiple*/
#endif
#ifdef fun_WDF_TIMER_6
extern EVT_WDF_TIMER fun_WDF_TIMER_6; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_1
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_2
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_3
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_4
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_5
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_6
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_6; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_7
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_7; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_8
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_8; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_9
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_9; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_10
extern EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE fun_WDF_WMI_INSTANCE_QUERY_INSTANCE_10; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_1
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_2
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_3
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_4
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_INSTANCE_5
extern EVT_WDF_WMI_INSTANCE_SET_INSTANCE fun_WDF_WMI_INSTANCE_SET_INSTANCE_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_1
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_2
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_3
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_4
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_SET_ITEM_5
extern EVT_WDF_WMI_INSTANCE_SET_ITEM fun_WDF_WMI_INSTANCE_SET_ITEM_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_1
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_1; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_2
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_2; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_3
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_3; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_4
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_4; /*multiple*/
#endif
#ifdef fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_5
extern EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD fun_WDF_WMI_INSTANCE_EXECUTE_METHOD_5; /*multiple*/
#endif
#ifdef fun_WDF_WMI_PROVIDER_FUNCTION_CONTROL
extern EVT_WDF_WMI_PROVIDER_FUNCTION_CONTROL fun_WDF_WMI_PROVIDER_FUNCTION_CONTROL; 
#endif
#ifdef fun_WDF_WORKITEM_1
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_1; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_2
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_2; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_3
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_3; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_4
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_4; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_5
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_5; /*multiple*/
#endif
#ifdef fun_WDF_WORKITEM_6
extern EVT_WDF_WORKITEM fun_WDF_WORKITEM_6; /*multiple*/
#endif
#ifdef fun_WDF_USB_READERS_FAILED_1
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_1; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READERS_FAILED_2
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_2; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READERS_FAILED_3
extern EVT_WDF_USB_READERS_FAILED fun_WDF_USB_READERS_FAILED_3; /*multiple*/ 
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_1
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_1; /*multiple*/  
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_2
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_2; /*multiple*/  
#endif
#ifdef fun_WDF_USB_READER_COMPLETION_ROUTINE_3
extern EVT_WDF_USB_READER_COMPLETION_ROUTINE fun_WDF_USB_READER_COMPLETION_ROUTINE_3; /*multiple*/  
#endif

#ifdef fun_WDF_DEVICE_RESOURCES_QUERY
extern EVT_WDF_DEVICE_RESOURCES_QUERY fun_WDF_DEVICE_RESOURCES_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY
extern EVT_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY fun_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY; 
#endif
#ifdef fun_WDF_DEVICE_EJECT
extern EVT_WDF_DEVICE_EJECT fun_WDF_DEVICE_EJECT; 
#endif
#ifdef fun_WDF_DEVICE_SET_LOCK
extern EVT_WDF_DEVICE_SET_LOCK fun_WDF_DEVICE_SET_LOCK; 
#endif
#ifdef fun_WDF_DEVICE_ENABLE_WAKE_AT_BUS
extern EVT_WDF_DEVICE_ENABLE_WAKE_AT_BUS fun_WDF_DEVICE_ENABLE_WAKE_AT_BUS; 
#endif
#ifdef fun_WDF_DEVICE_DISABLE_WAKE_AT_BUS
extern EVT_WDF_DEVICE_DISABLE_WAKE_AT_BUS fun_WDF_DEVICE_DISABLE_WAKE_AT_BUS; 
#endif
#ifdef fun_WDF_CHILD_LIST_CREATE_DEVICE
extern EVT_WDF_CHILD_LIST_CREATE_DEVICE fun_WDF_CHILD_LIST_CREATE_DEVICE; 
#endif
#ifdef fun_WDF_CHILD_LIST_SCAN_FOR_CHILDREN
extern EVT_WDF_CHILD_LIST_SCAN_FOR_CHILDREN fun_WDF_CHILD_LIST_SCAN_FOR_CHILDREN; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE; 
#endif
#ifdef fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP
extern EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP fun_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE; 
#endif
#ifdef fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP
extern EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP fun_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP; 
#endif
#ifdef fun_WDF_CHILD_LIST_DEVICE_REENUMERATED
extern EVT_WDF_CHILD_LIST_DEVICE_REENUMERATED fun_WDF_CHILD_LIST_DEVICE_REENUMERATED; 
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_1
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_1; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_2
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_2; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_3
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_3; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_4
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_4; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_5
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_5; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_6
extern EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS fun_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS_6; /*multiple*/
#endif
#ifdef fun_WDF_DEVICE_REMOVE_ADDED_RESOURCES
extern EVT_WDF_DEVICE_REMOVE_ADDED_RESOURCES fun_WDF_DEVICE_REMOVE_ADDED_RESOURCES; 
#endif
#ifdef fun_WDF_DRIVER_DEVICE_ADD
extern EVT_WDF_DRIVER_DEVICE_ADD fun_WDF_DRIVER_DEVICE_ADD; 
#endif


#ifdef fun_WDFDEVICE_WDM_PRE_PO_FX_UNREGISTER_DEVICE
extern EVT_WDFDEVICE_WDM_PRE_PO_FX_UNREGISTER_DEVICE fun_WDFDEVICE_WDM_PRE_PO_FX_UNREGISTER_DEVICE; 
#endif

#ifdef fun_WDFDEVICE_WDM_POST_PO_FX_REGISTER_DEVICE
extern EVT_WDFDEVICE_WDM_POST_PO_FX_REGISTER_DEVICE fun_WDFDEVICE_WDM_POST_PO_FX_REGISTER_DEVICE; 
#endif


#ifdef fun_IO_COMPLETION_ROUTINE_1
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_1; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_2
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_2; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_3
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_3; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_4
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_4; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_5
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_5; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_6
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_6; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_7
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_7; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_8
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_8; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_9
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_9; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_10
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_10; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_11
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_11; /*multiple*/
#endif

#ifdef fun_IO_COMPLETION_ROUTINE_12
extern IO_COMPLETION_ROUTINE fun_IO_COMPLETION_ROUTINE_12; /*multiple*/
#endif


#ifdef fun_PO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK
extern PO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK   fun_PO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK;
#endif

#ifdef fun_PO_FX_COMPONENT_IDLE_CONDITION_CALLBACK
extern PO_FX_COMPONENT_IDLE_CONDITION_CALLBACK   fun_PO_FX_COMPONENT_IDLE_CONDITION_CALLBACK;
#endif

#ifdef fun_PO_FX_COMPONENT_IDLE_STATE_CALLBACK
extern PO_FX_COMPONENT_IDLE_STATE_CALLBACK   fun_PO_FX_COMPONENT_IDLE_STATE_CALLBACK;
#endif

#ifdef fun_PO_FX_POWER_CONTROL_CALLBACK
extern PO_FX_POWER_CONTROL_CALLBACK   fun_PO_FX_POWER_CONTROL_CALLBACK;
#endif

#ifdef fun_PO_FX_COMPONENT_CRITICAL_TRANSITION_CALLBACK
extern PO_FX_COMPONENT_CRITICAL_TRANSITION_CALLBACK   fun_PO_FX_COMPONENT_CRITICAL_TRANSITION_CALLBACK;
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_1
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_1; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_2
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_2; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_3
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_3; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_4
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_4; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_5
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_5; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_6
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_6; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_7
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_7; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_8
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_8; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_9
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_9; /*multiple*/
#endif

#ifdef fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_10
extern DRIVER_NOTIFICATION_CALLBACK_ROUTINE fun_DRIVER_NOTIFICATION_CALLBACK_ROUTINE_10; /*multiple*/
#endif

#ifdef fun_POWER_SETTING_CALLBACK
extern POWER_SETTING_CALLBACK  fun_POWER_SETTING_CALLBACK;
#endif

