//  Copyright (c) Microsoft Corporation. All rights reserved.
//

//
//  SystemManagementContract.idl
//

namespace Windows.System
{
    [contractversion(2.0)]
    apicontract SystemManagementContract {};
}